# Install instructions : https://github.com/samtools/samtools/blob/develop/INSTALL
# Source from : http://www.htslib.org/download/
# Build with : "docker build -t samtools -f Dockerfile.samtools ."
# Run with : "docker run -it samtools samtools --help"

FROM ubuntu:22.04

# Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

# Upgrade ubuntu, install mandatory dependencies and clean
RUN \
    apt-get update && \
    apt-get upgrade -y -o Dpkg::Options::="--force-confold" && \
    apt-get install -y wget bzip2 autoconf automake make gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /data
WORKDIR /data/

RUN wget https://github.com/samtools/samtools/releases/download/1.16.1/samtools-1.16.1.tar.bz2 && \
		tar xjf samtools-1.16.1.tar.bz2 && \
		rm samtools-1.16.1.tar.bz2
RUN cd samtools-1.16.1/ && \ 
		./configure --prefix=/usr/local && \ 
		make && \ 
		make install && \ 
		rm -rf /data/samtools-1.16.1/

CMD ["samtools"]
