FROM ubuntu:22.04

RUN apt-get update --fix-missing \
&& apt-get install -y wget unzip make wget default-jre unzip perl 

RUN cd /usr/local \
&& wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip \
&& unzip fastqc_v0.11.9.zip \
&& rm fastqc_v0.11.9.zip \
&& chmod +x FastQC/fastqc 

RUN mkdir /data 
WORKDIR /data/
RUN ln -s /usr/local/FastQC/fastqc /usr/local/bin/fastqc

CMD ["fastqc"]
